/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package temperatureapp;

import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import org.jfree.chart.*;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author migue
 */
public class ChartUsers extends javax.swing.JFrame {

    /**
     * Creates new form ChartUsers
     */
    public ChartUsers() {
        initComponents();

        int reportedCount = 0;
        int registeredCount = 0;

        Connection con;
        MyConnection mcon = new MyConnection();
        con = mcon.returnConnection();
        String sql = "SELECT * FROM public.users";
        Statement stm;
        try {
            stm = con.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            while (rs.next()) {
                registeredCount++;
                if (rs.getBoolean("report")) {
                    reportedCount++;
                }
            }
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
            System.exit(0);
        }

        DefaultPieDataset dpd = new DefaultPieDataset();
        dpd.setValue("Reportados", reportedCount);
        dpd.setValue("Sin Reporte", registeredCount - reportedCount);
        JFreeChart jfc = ChartFactory.createPieChart("Estado de Usuarios", dpd, true, true, false);
        ChartPanel cp = new ChartPanel(jfc);

        chartPnl.setLayout(new java.awt.BorderLayout());
        chartPnl.add(cp, BorderLayout.CENTER);
        chartPnl.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chartPnl = new javax.swing.JPanel();
        betaLabel = new javax.swing.JLabel();
        tempLabel = new javax.swing.JLabel();
        engineLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chartPnl.setBackground(new java.awt.Color(204, 204, 204));
        chartPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(chartPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 800, 390));

        betaLabel.setBackground(new java.awt.Color(252, 202, 62));
        betaLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        betaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        betaLabel.setText("beta");
        betaLabel.setOpaque(true);
        betaLabel.setPreferredSize(new java.awt.Dimension(70, 30));
        getContentPane().add(betaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        tempLabel.setFont(new java.awt.Font("SansSerif", 1, 47)); // NOI18N
        tempLabel.setText("temp");
        getContentPane().add(tempLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        engineLabel.setFont(new java.awt.Font("SansSerif", 0, 47)); // NOI18N
        engineLabel.setText("engine");
        getContentPane().add(engineLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChartUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChartUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChartUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChartUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChartUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel betaLabel;
    private javax.swing.JPanel chartPnl;
    private javax.swing.JLabel engineLabel;
    private javax.swing.JLabel tempLabel;
    // End of variables declaration//GEN-END:variables
}
