/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package temperatureapp;

/**
 *
 * @author davidromero
 */
public class userReportFrame extends javax.swing.JFrame {

    /**
     * Creates new form userReportFrame
     */
    public userReportFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        usersTLabel = new javax.swing.JLabel();
        userTLabel = new javax.swing.JLabel();
        number1Label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        number2Label = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        number3Label = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        number4Label = new javax.swing.JLabel();
        graphicBtn = new javax.swing.JButton();
        footer2Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        footer1Panel = new javax.swing.JPanel();
        agendaBtn = new javax.swing.JButton();
        nuevoBtn = new javax.swing.JButton();
        headerPanel = new javax.swing.JPanel();
        engineLabel = new javax.swing.JLabel();
        tempLabel = new javax.swing.JLabel();
        betaLabel = new javax.swing.JLabel();
        monitorBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(196, 196, 196));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usersTLabel.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        usersTLabel.setText("Usuarios");
        mainPanel.add(usersTLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        userTLabel.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        userTLabel.setText("Registrados");
        mainPanel.add(userTLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        number1Label.setFont(new java.awt.Font("SansSerif", 0, 95)); // NOI18N
        number1Label.setText("1");
        number1Label.setToolTipText("");
        mainPanel.add(number1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel2.setText("Accesos");
        mainPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel3.setText("A la aplicación");
        mainPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel4.setText("este dia");
        mainPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        number2Label.setFont(new java.awt.Font("SansSerif", 0, 95)); // NOI18N
        number2Label.setText("15");
        mainPanel.add(number2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel6.setText("Accesos");
        mainPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel7.setText("A la aplicación");
        jLabel7.setToolTipText("");
        mainPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, -1, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel8.setText("Histórico");
        mainPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, -1, -1));

        number3Label.setFont(new java.awt.Font("SansSerif", 0, 95)); // NOI18N
        number3Label.setText("112");
        mainPanel.add(number3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, -1, -1));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel10.setText("Usuarios");
        mainPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 70, -1, -1));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel11.setText("Reportados");
        mainPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 90, -1, -1));

        number4Label.setFont(new java.awt.Font("SansSerif", 0, 95)); // NOI18N
        number4Label.setText("112");
        mainPanel.add(number4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 170, -1, -1));

        graphicBtn.setBackground(new java.awt.Color(0, 0, 0));
        graphicBtn.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        graphicBtn.setForeground(new java.awt.Color(255, 255, 255));
        graphicBtn.setText("Ver gráfica.");
        graphicBtn.setBorder(null);
        graphicBtn.setBorderPainted(false);
        graphicBtn.setOpaque(true);
        graphicBtn.setPreferredSize(new java.awt.Dimension(330, 60));
        graphicBtn.setSize(new java.awt.Dimension(29, 29));
        mainPanel.add(graphicBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        backgroundPanel.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 1280, 340));

        footer2Panel.setBackground(new java.awt.Color(255, 255, 255));
        footer2Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel1.setText("REPORTAR USUARIO CON ID");
        footer2Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel5.setText("ELIMINAR REPORTE CON ID");
        footer2Panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 165, -1, -1));

        jTextField1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.setPreferredSize(new java.awt.Dimension(380, 50));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        footer2Panel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 85, -1, -1));

        jTextField2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField2.setPreferredSize(new java.awt.Dimension(380, 50));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        footer2Panel.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jButton1.setBackground(new java.awt.Color(252, 202, 62));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jButton1.setText("enviar.");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setOpaque(true);
        jButton1.setPreferredSize(new java.awt.Dimension(180, 50));
        footer2Panel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 85, -1, -1));

        jButton2.setBackground(new java.awt.Color(252, 202, 62));
        jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 30)); // NOI18N
        jButton2.setText("enviar.");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setOpaque(true);
        jButton2.setPreferredSize(new java.awt.Dimension(180, 50));
        footer2Panel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, -1));

        backgroundPanel.add(footer2Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, 640, 300));

        footer1Panel.setBackground(new java.awt.Color(226, 226, 226));
        footer1Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agendaBtn.setBackground(new java.awt.Color(0, 0, 0));
        agendaBtn.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        agendaBtn.setForeground(new java.awt.Color(255, 255, 255));
        agendaBtn.setText("Agenda");
        agendaBtn.setBorderPainted(false);
        agendaBtn.setOpaque(true);
        agendaBtn.setPreferredSize(new java.awt.Dimension(180, 60));
        footer1Panel.add(agendaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        nuevoBtn.setBackground(new java.awt.Color(10, 146, 255));
        nuevoBtn.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        nuevoBtn.setText("Nuevo");
        nuevoBtn.setBorderPainted(false);
        nuevoBtn.setOpaque(true);
        nuevoBtn.setPreferredSize(new java.awt.Dimension(180, 60));
        footer1Panel.add(nuevoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, -1));

        backgroundPanel.add(footer1Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 640, 300));

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        engineLabel.setFont(new java.awt.Font("SansSerif", 0, 47)); // NOI18N
        engineLabel.setText("engine");
        headerPanel.add(engineLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        tempLabel.setFont(new java.awt.Font("Lucida Grande", 1, 47)); // NOI18N
        tempLabel.setText("temp");
        headerPanel.add(tempLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        betaLabel.setBackground(new java.awt.Color(252, 202, 62));
        betaLabel.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        betaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        betaLabel.setText("beta");
        betaLabel.setOpaque(true);
        betaLabel.setPreferredSize(new java.awt.Dimension(70, 30));
        headerPanel.add(betaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        monitorBtn.setBackground(new java.awt.Color(0, 0, 0));
        monitorBtn.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        monitorBtn.setForeground(new java.awt.Color(255, 255, 255));
        monitorBtn.setText("monitor.");
        monitorBtn.setBorder(null);
        monitorBtn.setBorderPainted(false);
        monitorBtn.setOpaque(true);
        monitorBtn.setPreferredSize(new java.awt.Dimension(175, 60));
        monitorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monitorBtnActionPerformed(evt);
            }
        });
        headerPanel.add(monitorBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 60, -1, -1));

        exitBtn.setBackground(new java.awt.Color(252, 202, 62));
        exitBtn.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        exitBtn.setText("salir.");
        exitBtn.setBorder(null);
        exitBtn.setBorderPainted(false);
        exitBtn.setOpaque(true);
        exitBtn.setPreferredSize(new java.awt.Dimension(175, 60));
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        headerPanel.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 60, -1, -1));

        backgroundPanel.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        extiFrame ef = new extiFrame();
        ef.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void monitorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monitorBtnActionPerformed
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_monitorBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userReportFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agendaBtn;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel betaLabel;
    private javax.swing.JLabel engineLabel;
    private javax.swing.JButton exitBtn;
    private javax.swing.JPanel footer1Panel;
    private javax.swing.JPanel footer2Panel;
    private javax.swing.JButton graphicBtn;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton monitorBtn;
    private javax.swing.JButton nuevoBtn;
    private javax.swing.JLabel number1Label;
    private javax.swing.JLabel number2Label;
    private javax.swing.JLabel number3Label;
    private javax.swing.JLabel number4Label;
    private javax.swing.JLabel tempLabel;
    private javax.swing.JLabel userTLabel;
    private javax.swing.JLabel usersTLabel;
    // End of variables declaration//GEN-END:variables
}
