/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package temperatureapp;

import java.sql.Connection;
import java.sql.PreparedStatement;

/**
 *
 * @author davidromero
 */
public class UserRegister extends javax.swing.JFrame {

    /**
     * Creates new form UserRegister
     */
    public UserRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        engineLabel = new javax.swing.JLabel();
        tempLabel = new javax.swing.JLabel();
        betaLabel = new javax.swing.JLabel();
        namesTextField = new javax.swing.JTextField();
        lastTextField = new javax.swing.JTextField();
        userTextField = new javax.swing.JTextField();
        passwordInitial = new javax.swing.JPasswordField();
        NameLabel = new javax.swing.JLabel();
        LastNameLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar usuario");
        setMinimumSize(new java.awt.Dimension(640, 800));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(640, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        engineLabel.setFont(new java.awt.Font("SansSerif", 0, 47)); // NOI18N
        engineLabel.setText("engine");
        jPanel1.add(engineLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        tempLabel.setFont(new java.awt.Font("SansSerif", 1, 47)); // NOI18N
        tempLabel.setText("temp");
        jPanel1.add(tempLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        betaLabel.setBackground(new java.awt.Color(252, 202, 62));
        betaLabel.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        betaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        betaLabel.setText("beta");
        betaLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        betaLabel.setOpaque(true);
        jPanel1.add(betaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 90, 40));

        namesTextField.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        namesTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        namesTextField.setPreferredSize(new java.awt.Dimension(380, 50));
        jPanel1.add(namesTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        lastTextField.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lastTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lastTextField.setPreferredSize(new java.awt.Dimension(380, 49));
        lastTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(lastTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        userTextField.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        userTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        userTextField.setPreferredSize(new java.awt.Dimension(380, 50));
        userTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(userTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, -1, -1));

        passwordInitial.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        passwordInitial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        passwordInitial.setPreferredSize(new java.awt.Dimension(380, 50));
        jPanel1.add(passwordInitial, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, -1, -1));

        NameLabel.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        NameLabel.setText("NOMBRES");
        jPanel1.add(NameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        LastNameLabel.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        LastNameLabel.setText("APELLIDOS");
        jPanel1.add(LastNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        userLabel.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        userLabel.setText("USUARIO");
        jPanel1.add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, -1, -1));

        passwordLabel.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        passwordLabel.setText("CLAVE");
        jPanel1.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, -1, -1));

        registerButton.setBackground(new java.awt.Color(252, 202, 62));
        registerButton.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        registerButton.setText("enviar.");
        registerButton.setBorder(null);
        registerButton.setOpaque(true);
        registerButton.setPreferredSize(new java.awt.Dimension(180, 50));
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 700, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lastTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastTextFieldActionPerformed

    private void userTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTextFieldActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        Connection con;
        try {
            MyConnection mcon = new MyConnection();
            con = mcon.returnConnection();
            String sql = "INSERT into public.users (username,clave,nombres,apellidos,report) VALUES (?,?,?,?,?)";
            PreparedStatement stm = con.prepareStatement(sql);
            stm.setString(1, userTextField.getText());
            stm.setString(2, passwordInitial.getText());
            stm.setString(3, namesTextField.getText());
            stm.setString(4, lastTextField.getText());
            stm.setBoolean(5, false);
            stm.execute();
            con.close();
            LoginFrame lf = new LoginFrame();
            lf.setVisible(true);
            this.dispose();
        } catch (Exception e) {
            System.err.println("Got an exception!");
            System.err.println(e.getMessage());
        }
// TODO add your handling code here:
    }//GEN-LAST:event_registerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel betaLabel;
    private javax.swing.JLabel engineLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastTextField;
    private javax.swing.JTextField namesTextField;
    private javax.swing.JPasswordField passwordInitial;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel tempLabel;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField userTextField;
    // End of variables declaration//GEN-END:variables
}
